### ISSUE TITLE
Splunk.Client is not the signed assembly

### ISSUE THREAD

**Issue by amos42** [splunk/splunk-sdk-csharp-pcl#102]
Splunk.Client is not the signed assembly.
So this cannot be used in other signed assemblies.
This problem means there is a limit to where this library can be used.
Recommend distributing a Nuget containing a signed assembly.

**Comment by ncanumalla-splunk** [comment]
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.
