### ISSUE TITLE
Issue in ASP.NET MVC controller action

### ISSUE THREAD

**Issue by ThiloL** [splunk/splunk-sdk-csharp-pcl#107]
Like mentioned here https://community.splunk.com/t5/Archive/Async-deadlock-issues-using-Splunk-Client-with-ASP-NET/m-p/286560 LogOnAsync doesn't work in an ASP.NET MVC controller action. Something goes wrong with the threads.

Is there a workaround?

**Comment by ncanumalla-splunk** [comment]
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.
