### ISSUE TITLE
Exception: Read </results> where <result> or <response> was expected.

### ISSUE THREAD

**Issue by YulerB** [splunk/splunk-sdk-csharp-pcl#110]
Error raised by Splunk Client .net core version :
Read ``</results>`` where ``<result>`` or ``<response>`` was expected.

When executing: 
using (SearchResultStream results = await client.ExportSearchResultsAsync(search, searchExportArgs))

**Comment by YulerB** [comment]
I managed to get a trace:

Method: GET, RequestUri: 'https://splunk:7089/services/search/jobs/export?search=search index%3Dvast sourcetype%3Dvast%3A eventtype%3Dvast_detection_event earliest%3D1634870997 latest%3D1634871222 | sort 500000 %2B _indextime&f=HOST_ID&f=IP&f=PORT&f=PROTOCOL&f=TRACKING_METHOD&f=TYPE&f=severity&f=_indextime&f=_time&f=_cd&max_count=5000', Version: 1.1, Content: <null>, Headers:
{
  Cookie: splunkd_7089=NDgRyfr4E7LciL7MTXmk0CTt7jkmp83QMMuzHVt_AqfvF004Ss2VjZmFmMY_cnu33RHj_jwomfeRuZruHTa5m_mtPJh8IqJopYiDvM9f^EzNeVdofdbkA9Mk79sSaN7MsdL
  User-Agent: splunk-sdk-csharp/2.2.8
}
<?xml version='1.0' encoding='UTF-8'?>
<results preview='0'>
<meta>
<fieldOrder>
<field>HOST_ID</field>
<field>IP</field>
<field>PORT</field>
<field>PROTOCOL</field>
<field>TRACKING_METHOD</field>
<field>TYPE</field>
<field>severity</field>
<field>_indextime</field>
<field>_time</field>
<field>_cd</field>
</fieldOrder>
</meta>
<messages>
  <msg type="INFO">Your timerange was substituted based on your search string</msg>
</messages>
</results>

Throws error:
Read </results> where <result> or <response> was expected.

Also the user agent is not what I expected, probably should have been something like: splunk-sdk-csharp-core/1.0.7

**Comment by YulerB** [comment]
Splunk Server 
Version: 8.2
Build: e053ef3c985f

**Comment by ncanumalla-splunk** [comment]
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.
