### ISSUE TITLE
C# SDK, XmlReaderExtensions throws exception when reading fields that use tags

### ISSUE THREAD

**Issue by travis134** [splunk/splunk-sdk-csharp-pcl#36]
When getting started with the Splunk C# SDK I ran into an issue where the following exception would be thrown for certain search queries:
 
"Read charater data where <value> or <v> was expected"
 
Upon further investigation I determined that the issue was occurring when reading fields that made use of tags:
<field k='source'>
    <value><text>xboxvideo</text><tag>XBV</tag></value>
</field>
 
When removing the tag from this field, search results were parsed without exception.
 
Is this a known issue with the C# SDK? Right now I’ve worked around this by removing tags from our fields, but that’s obviously not a preferable solution as tags are quite handy for writing more complicated queries.
 
Thanks,
-travis

**Comment by glennblock** [comment]
Hi @travis134 sounds like a bug, we'll look into it.

**Comment by glennblock** [comment]
Thanks for reporting this!

**Comment by sethisernhagen** [comment]
Is there a work around for this?  Not being able to use global tags and the sdk is pretty rough.

**Comment by itay** [comment]
Hi @sethisernhagen - sorry for the lack of updates. We have a fix in mind, but
we're working hard towards .conf next week, and hope we can have a fix out soon
after. 

As always, we're happy and open to pull requests as well.

Thanks!

**Comment by nhennebe67** [comment]
I encountered the same bug.
My temporary fix was to comment out this line
//r.EnsureMarkup(XmlNodeType.Element, "value", "v");

in class SearchResult 

I hope we can have the proper fix in Nuget soon!

>>>>

       public async Task ReadXmlAsync(XmlReader reader)
        {
            Contract.Requires<ArgumentNullException>(reader != null, "reader");

            reader.MoveToElement();
            reader.EnsureMarkup(XmlNodeType.Element, "result");

            this.Object = new ExpandoObject();
            var dictionary = (IDictionary<string, object>)this.Object;

            this.SegmentedRaw = null;

            await reader.ReadEachDescendantAsync("field", async (r) =>
            {
                var key = r.GetRequiredAttribute("k");
                var values = new List<string>();
                var fieldDepth = r.Depth;

                while (await r.ReadAsync().ConfigureAwait(false))
                {
                    if (r.Depth == fieldDepth)
                    {
                        break;
                    }

                    Debug.Assert(r.Depth > fieldDepth, "This loop should have exited earlier.");

					//r.EnsureMarkup(XmlNodeType.Element, "value", "v");

					if (r.Name == "value")
					{
						if (await r.ReadToDescendantAsync("text").ConfigureAwait(false))
						{
							values.Add(await r.ReadElementContentAsStringAsync().ConfigureAwait(false));
						}
					}
					else if (r.Name == "v")
					{
						Debug.Assert(this.SegmentedRaw == null);
						Debug.Assert(key == "_raw");

						string value = await r.ReadOuterXmlAsync().ConfigureAwait(false);
						this.SegmentedRaw = XElement.Parse(value);
						values.Add(this.SegmentedRaw.Value);
					}
                }

                switch (values.Count)
                {
                    case 0: 
                        dictionary.Add(key, null);
                        break;
                    case 1:
                        dictionary.Add(key, values[0]);
                        break;
                    default:
                        dictionary.Add(key, new ReadOnlyCollection<string>(values));
                        break;
                }
            }).ConfigureAwait(false);
        }

Thanks!

**Comment by shakeelmohamed** [comment]
We've just released v2.2.1 addressing this, thanks for the bug report @travis134!
