### ISSUE TITLE
How to insert/delete KV data?

### ISSUE THREAD

**Issue by Caldas** [splunk/splunk-sdk-csharp-pcl#46]
I would like to know how can I manipulate data from KV collections using C# SDK.

**Comment by itay** [comment]
@Caldas we do not currently have support in the C# SDK for the KV Store REST API. We're always open to a Pull Request to add this capability.

**Comment by glennblock** [comment]
Hi @Caldad

We have a generic set of APIs in our SDK you should be able to use for
calling K/V store.

I will look into this for you.

**Comment by glennblock** [comment]
Hi @Caldas 

Here is an example showing the general purpose API I was talking about. It allows you to work with all our REST APIs, so potentially it will work: https://github.com/splunk/splunk-sdk-csharp-pcl/blob/master/examples/Get-SplunkDataInput/Program.cs. This example shows restarting a data input, something we don't support in the SDK.

**Comment by glennblock** [comment]
OK, I've looked into this further, and it can work. I've created a gist for you here to show you how: https://gist.github.com/glennblock/655fc417fd84b47b5bd9

This example shows creating a new collection in K/V store, adding an item to it, and then querying the collection. You can also do other operations like querying for specific keys, or replacing keys with some tweaks.

**Comment by Caldas** [comment]
Thanks @glennblock your comments helped a lot.

Just another point, how can I delete data from KV using this REST API approach?

**Comment by Caldas** [comment]
Sorry @glennblock I found how to delete using **_service.Context.DeleteAsync**

Thanks for your help ..

**Comment by glennblock** [comment]
Sure! You've helped me create what will be a new blog post :-)
