### ISSUE TITLE
Hangs when enumerating stream

### ISSUE THREAD

**Issue by JeremyButts** [splunk/splunk-sdk-csharp-pcl#54]
Version: 2.2.3
Platform: ASP.NET MVC 5
Framework: .Net 4.5 Visual Studio 2015 
Splunk: 6.3.3

After performing a one shot search that returns no results (e.g. `<results />`) and then enumerating over the SearchResultStream the application hangs. No exception is thrown.

**Comment by shakeelmohamed** [comment]
Thanks for the bug report @JeremyButts, we will look into this. In the meantime, we're open to a pull request if you want to take a look
