### ISSUE TITLE
JobCollection CreateAsync mode

### ISSUE THREAD

**Issue by JeremyButts** [splunk/splunk-sdk-csharp-pcl#55]
Version: 2.2.3
Does not look like **mode** is being used in the CreateAsync method on line 172 in JobCollection.cs.  I did not see when I set the value to blocking and observed the request with Fiddler.

**Comment by ncanumalla-splunk** [comment]
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.
