### ISSUE TITLE
ExportSearchResultsAsync returns InvalidDataException when no data 

### ISSUE THREAD

**Issue by drano** [splunk/splunk-sdk-csharp-pcl#62]
After call ExportSearchResultsAsync and this search not found data, I try to get a list of results with 
`var results = searchResultStream.AsEnumerable().ToList()`

This error is raised:
System.IO.InvalidDataException: Read </results> where <result> or <response> was expected.

I am using package 2.2.5

**Comment by shakeelmohamed** [comment]
@drano can you show us an example program that reproduces this issue?
