### ISSUE TITLE
Method EventWriter.QueueEventForWriting is not thread-safe

### ISSUE THREAD

**Issue by andrew-kuzovov** [splunk/splunk-sdk-csharp-pcl#63]
Method EventWriter.QueueEventForWriting is claimed thread-safe, but **actually it is not** because of non-thread-safe eventQueueMonitor initialization inside.

**Comment by shakeelmohamed** [comment]
Thanks for the issue @andrew-kuzovov, we'd welcome a pull request if you're interested in speeding up the process. Otherwise, we will look at it once we have some time

**Comment by ncanumalla-splunk** [comment]
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.
