### ISSUE TITLE
LogOnAsync("hostname", "password") is returning null response

### ISSUE THREAD

**Issue by SaiSK88** [splunk/splunk-sdk-csharp-pcl#72]
Hi All,

I am using Spluck C# SDK 2.2.5 with Visual Studio 2017. Below is the code,

Service service = new Service(Scheme.Https, "localhost", 8089); 
await service.LogOnAsync("admin", "adminone");
var searchResults = await service.SearchOneShotAsync("search index=_internal | head 10");

I am getting Null response for await service.LogOnAsync("username", "password") method.

The Splunk REST API is working fine. I verified it by running it through curl command,
curl -k https://localhost:8089/services/auth/login -d username=admin -d password=adminone

I am able to get sessionKey using above curl command, however I am getting null response for LogOnAsync method.

Any suggestion on what could be missing here and how to fix it?

Thanks in advance.

Regards,
Sai

**Comment by tdhellmann** [comment]
Hi Sai, 

I assume this is on a development machine, right? You may be running into a certificate issue. In the examples that ship with the C# SDK, typically you will see this being done before connection: 

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls;
ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) =>
            {
                return true;
            };

Are you already using that workaround and still seeing this error? If so, can you also let me know what version of Splunk you're trying to connect to? 

Best, 

-Tedd

**Comment by SaiSK88** [comment]
Hi Tedd,

Thanks for the quick reply.

I am using development machine, but I did not get any exception on Certificate Issue.
Could you please let me know where do I need to put below code to check if it solves the issue,,

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls;
ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) =>
{
return true;
};

I am using Splunk 6.4 which is running on the same machine.

Regards,
Sai

**Comment by vicarrara** [comment]
Hey Guys,

Any solution for this issue?

I have the same problem with my solution

Regards,

**Comment by ncanumalla-splunk** [comment]
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.
