### ISSUE TITLE
Issue in Search with Push model 

### ISSUE THREAD

**Issue by mohsenvafa** [splunk/splunk-sdk-csharp-pcl#86]
In Search with Push Model, when you subscribe to the stream, the onNext is never called unless you iterate over all the result. 
https://github.com/splunk/splunk-sdk-csharp-pcl/blob/25381ab45877dcb0e26cac22d55d30ff3ffb1c3b/examples/normal-search/Program.cs#L77

That means if you comment out lines 56-59, the observable stream will never be executed https://github.com/splunk/splunk-sdk-csharp-pcl/blob/25381ab45877dcb0e26cac22d55d30ff3ffb1c3b/examples/normal-search/Program.cs#L56-L59

**Comment by ncanumalla-splunk** [comment]
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.
