### ISSUE TITLE
another issue in the Atomic reader

### ISSUE THREAD

**Issue by MACKAT05** [splunk/splunk-sdk-csharp-pcl#88]
this Entry
name ".execute_input.flush_prestats" string
causes a failure in the normalise dictionary name method...

This happens whenever the Tstats command is used in a returned search

Have fix:
will open a pull request soon.

**Comment by shilpabijam** [comment]
Sure, thanks for reporting this issue @MACKAT05 .

**Comment by fantavlik** [comment]
Hi @MACKAT05 if you have a fix or more context for this issue please reach out, I'm closing this until then.
