### ISSUE TITLE
Cannot see dev.splunk.com/csharp

### ISSUE THREAD

**Issue by VladPavliuk** [splunk/splunk-sdk-csharp-pcl#97]
I see 403 error when I try to visit:
http://dev.splunk.com/csharp

![Annotation 2019-11-19 180749](https://user-images.githubusercontent.com/24705251/69163795-856e0000-0af7-11ea-90c8-03bc491ef138.png)

**Comment by fantavlik** [comment]
Hey @VladPavliuk this is the correct link: https://dev.splunk.com/enterprise/docs/csharp
