### ISSUE TITLE
How to deal with non default base path ?

### ISSUE THREAD

**Issue by bklooste** [splunk/splunk-sdk-csharp-pcl#98]
Security have blocked the api port and made it available on a different url but i dont see any options on how to set that ..  The path from the Uri overload seems to be ignored. 

I dont see this documented anywhere... though i can hit the url with curl / raw http.  Was thinking a custom MessageHandler but that seems pretty  ugly..

**Comment by ncanumalla-splunk** [comment]
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.
